version: '2'

services:
  db:
    image: "mysql:5.7"
    restart: always
    environment:
     MYSQL_ROOT_PASSWORD: root
     MYSQL_USERNAME: root
     MYSQL_PASSWORD: root
        - '3306:3306'
    expose:
      - '3306'
    volumes:
      - db:/var/run/mysqld
    ports:
      - "33061:3306"

  redis:
    image: redis:5.0-alpine
    command: redis-server
    volumes:
      - redis:/data
    ports:
      - 6379

  sidekiq:
    build: .
    command: bundle exec sidekiq
    depends_on:
      - 'redis'
    env_file:
      - .env

  myapp: 
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports: 
      - "3001:3000"
    depends_on:
      - db
      - redis
    links:
      - db
      - redis
    env_file:
      - .env
    volumes: 
      - ".:/myapp"
volumes:
  db:
  redis: