version: '2'

services:
  db:
    image: "mysql:5.7"
    restart: always
    environment:
     MYSQL_ROOT_PASSWORD: root
     MYSQL_USERNAME: root
     MYSQL_PASSWORD: root
        - '3306:3306'
    expose:
      - '3306'
    volumes:
      - db:/var/run/mysqld
    ports:
      - "33061:3306"

  redis:
    image: redis:5.0-alpine
    command: redis-server
    volumes:
      - redis:/data
    ports:
      - 6379

  sidekiq:
    build: .
    command: bundle exec sidekiq
    depends_on:
      - 'redis'
    env_file:
      - .env

  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.4
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=es01
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200


  # kib01:
  #   image: docker.elastic.co/kibana/kibana:7.17.4
  #   container_name: kib01
  #   ports:
  #     - 5601:5601
  #   environment:
  #     ELASTICSEARCH_URL: http://es01:9200
  #     ELASTICSEARCH_HOSTS: '["http://es01:9200"]'
  #   networks:
  #     - elastic

  myapp: 
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports: 
      - "3001:3000"
    depends_on:
      - db
      - redis
      - es01
    links:
      - db
      - redis
    env_file:
      - .env
    volumes: 
      - ".:/myapp"
volumes:
  db:
  redis:
  data01:
    driver: local